### ISSUE TITLE
Use latest avro package?

### ISSUE THREAD

**Issue by istathar** [target/theta-idl#3]
Would you accept a patch that would bump the **avro** dependency to the latest (which is 0.5.2)? Right now your _theta.cabal_ file is holding you to `< 0.4.7`.

I did a `stack build` with lts-18.21 and `>= 0.5.2` and while there were compile failures they didn't seem related to Data.Avro so using package that Alexey is now maintaining seems a good bet.

```
/home/andrew/vcs/haskell/theta-idl/theta/src/Theta/Metadata.hs:63:31: error:
    • Couldn't match type ‘[a0]’ with ‘Maybe Text.Text’
      Expected type: Test.QuickCheck.Gen.Gen (Maybe Text.Text)
        Actual type: Test.QuickCheck.Gen.Gen [a0]
```

**Comment by TikhonJelvis** [comment]
Yeah, bumping to a new version of Avro makes sense. I had a specific reason for that bound, but I don't remember what it was, so I figure it'll be fine as long as the code builds and the tests pass :).

In the meantime, I'll look at the compile failures. A few housekeeping tasks for this project (like moving off of `language-rust`, which was causing build issues) fell off my to-do list, but I'll have time over the next two weeks to catch up on that.

Just a heads up: Target has a contributor licensing agreement (CLA) for PRs, so when you open a PR, a bot will add a link where you can sign the agreement. I just realized that I should add a note about this to README.md or CONTRIBUTING.md so that it isn't a surprise.

**Comment by TikhonJelvis** [comment]
Turns out the new version of `avro` required a bunch of code changes in Theta, but luckily the changes were all pretty mechanical. Could you take a look at #5 and tell me if it makes sense and builds for you with Stack? Thanks!

Rust support is broken, but I'm pretty sure that's not related to the PR.

**Comment by istathar** [comment]
... and there's an **avro** 0.6.0 out. We'll check with that, too, but otherwise we can close this.

**Comment by istathar** [comment]
We are still encountering the problem arising from the **versions** package cited above.

**Comment by TikhonJelvis** [comment]
Sounds good. I'll take a closer look tomorrow—I guess the pinned version of **versions** was older even after I updated the version of Nixpkgs itself that I was using. I'll have to either update the code on my end or add some version constraints to the `theta.cabal` file.
