### ISSUE TITLE
Enhancement: Datetime and other logical types

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#48]
We have been using `String` for `uuid`s, as there seems to be no logical type implementation in **theta** yet. However, we now noticed `Datetime` does not get parsed into `avdl`, which was a surprise, given that **theta** does implement that for, say, Haskell. Here's a minimal example:

`animal.theta`
```
language-version: 1.1.0
avro-version: 1.0.0

---

type Cat = Datetime
```

`roar.sh`
```
#!/usr/bin/env bash

export THETA_LOAD_PATH=${PWD}

theta avro type -t animal.Cat -o cat.avsc
```

Running the above bash script creates a new file,

`cat.avsc`
```
"long"
```

I would expect to instead see something more akin

```
{
  "type": "long",
  "logicalType": "timestamp-millis"
}
```

**Comment by TikhonJelvis** [comment]
Yep, supporting additional logical types is on my to-do list. Definitely `uuid`,  `time-micros` and `local-timestamp-micros`. Not sure about how to handle the `-millis` versions of the time types, and `duration` might have to wait until I figure out how to support fixed-width types in general.

> However, we now noticed `Datetime` does not get parsed into `avdl`...

Right, the module needs to have `avro-version` ≥ 1.1.0 for that to work.

One of my goals is that the Avro generated by Theta modules should not change semantically between different Theta releases without explicitly changing the `avro-version` setting *for that module*.

The versioning logic should work on a per-module basis, so if you define a newtype like `type Cat = Datetime`, it should compile to either `long` or `timestamp-millis` depending on the `avro-version` set in `animal.theta`, even when you import `animal.theta` from a different module. Pretty sure I have some tests covering that, but I'd have to double-check; I've definitely tested it for record fields.

This versioning approach was pretty useful when using Theta internally at Target, but I had a pretty well-defined release process there; since open-sourcing the release process has been ambiguous. For now, I've decided that 1.0.0 refers to the semantics Theta had when it got open-sourced (I reset the version numbers as part of the open-sourcing process :)), so I've been putting my additional changes into 1.1.0.

I'll have an “official” release soon—I was thinking of doing it after adding support for the remaining logical types—and any new changes after that will require `avro-version` ≥ 1.2.0 (or, if it's a breaking change, ≥ 2.0.0).

**Comment by pasunboneleve** [comment]
It would be great to have a place in the documentation mapping versions to features.

**Comment by TikhonJelvis** [comment]
Good call. Created #49 as a reminder.

**Comment by pasunboneleve** [comment]
That's what I have now:

`cat.theta`
```
language-version: 1.1.0
avro-version: 1.1.0

---

type Cat = Datetime
```

`cat.avsc`
```
{"logicalType":"timestamp-micros","type":"long"}
```
and after `npx avro-ts cat.avsc` I get

`cat.avsc.ts`
```
export type AvroType = number;
```

So yeah, **TypeScript** support would be greatly appreciated.

**Comment by TikhonJelvis** [comment]
Added support for UUIDs (in modules with `language-version` ≥ 1.1.0) in #52

**Comment by TikhonJelvis** [comment]
Added Time (#56 and #57) as well as LocalDatetime (#58), also requiring `language-version` ≥ 1.1.0.

My plan right now is to add `Duration`, fixed-size types and *maybe* `Decimal` before creating an “official” release for 1.1.0. After that point, further backwards-compatible changes to the language will be part of `language-version` 1.2.0.
