### ISSUE TITLE
Support union type in theta

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#50]
We would like to define all the possible types that could be present in a stream. This would represent an `union` of types. In Haskell it would be just a sum type, where each type constructor encoded a separate type with its own typeclasses, etc. In Avro that construct doesn't translate to `enum`, as `enum` is a shallow set of constructors that cannot reference a type.

We have discussed a potential use of this construct in a former issue. I believe **theta-ldl**'s current implementation doesn't open that possibility.

> Deduplicated Avro definitions would be useful for passing to other commands in general—not just Typescript. Seems more useful than what `theta avro all`  does today. We could return a JSON list with an entry for each type defined in a set of modules. This is valid as an `.avsc` file and I've seen people recommend this as a way to define multiple schemas in a single file—if I'm understanding the [Avro specification correctly][1] this would technically define a union of all the types.
[1]: https://avro.apache.org/docs/current/spec.html#schemas

_Originally posted by @TikhonJelvis in https://github.com/target/theta-idl/issues/42#issuecomment-1062411998_

**Comment by TikhonJelvis** [comment]
Are the types coming from some schema defined externally?

**Comment by TikhonJelvis** [comment]
One thing worth noting: the binary encoding for a variant in Theta is always identical to the corresponding Avro union. The Avro schema has an extra record with a single field, but, as a consequence of how records are encoded in Avro[^avro-records], the binary encoding of the record is always identical to the binary encoding of the value in the field.

The following Theta type:

```
type ExampleUnion = A String | B Int
```

will parse and encode exactly the same as the corresponding Avro union:

``` json
["string", "int"]
```

The Avro schema generated for `ExampleUnion` will have some extra record wrappers, but these only affect *the schema*, not the binary format.

Every Avro union can be expressed as a Theta variant. Avro unions have some additional limitations that Theta unions don't; for example, we can have the same type multiple times:

```
type ExampleUnion = A String | B String
```

this *would* logically correspond to the following Avro union:

``` json
["string", "string"]
```

...except that Avro unions [explicitly can't have duplicate types][avro-union-duplicate]. Avro unions also can't have more than one map/array type and can't be nested.

What this means in practice is that while we can always write a Theta variant that corresponds to an Avro union of primitive types, some Theta variants would need wrapper records to be valid in Avro. One way to see this is that Theta *always* generates wrapper types—whether it needs them or not—which lets it avoid the limitations of "raw" Avro unions.

I can definitely see how the extra records that Theta generates in its Avro schemas for variants are confusing. I'd love to come up with a more intuitive encoding, but I could not figure out a satisfying design last time I tried. In the meantime, it seems like variants should be *sufficient* for reading/writing whatever Avro you'd like[^except]—the binary format will be the same, but there might be some inconvenience with other tools that process Avro schemas.

[^avro-records]: In particular, an Avro record is encoded by [concatenating the values for each field in order][encoding-complex-types]. There's no extra encoding for the record itself—the record just exists in the schema, and we have to have the schema to decode the binary values at all.

[encoding-complex-types]: https://avro.apache.org/docs/current/spec.html#binary_encode_complex

[avro-union-duplicate]: https://avro.apache.org/docs/current/spec.html#Unions

[^except]: ...any Avro you'd like except for fixed-size binary types, which are an orthogonal question to unions and shouldn't be hard to support in the near future.

**Comment by pasunboneleve** [comment]
> Are the types coming from some schema defined externally?

No, we're defining everything with Theta. I probably didn't realise I could do 
```
type Example = A String | B Int
```
Another entry for the docs? 😉

**Comment by TikhonJelvis** [comment]
Oh, sorry, just realized that syntax isn't quite right—too much Haskell on my mind :P

You'd need to give the `String` and `Int` field names:

```
type Example = A { a : String } | B { b : String }
```

The semantics and behavior I talked about is still the same. The field names get used in the generated Avro schema and in code generation, but they don't change the binary encoding at all.

**Comment by pasunboneleve** [comment]
Well actually what I need is
```
type A = {
    aField : String
}

type B = {
    bField : Int
}

type ExampleUnion = Ah { a : A } | Boo { b: B }
```
A bit cumbersome, but if you tell me that works, that's what I'll be doing.

**Comment by TikhonJelvis** [comment]
Yep, modulo some syntax errors, that should work.

It's the same as what you'd get with a sum type in Haskell, except each of the constructors has to use record syntax with named fields. Always needing field names in sum types can get a bit awkward, but it helps make the code and schema generation more explicit.

Just thinking about it now, one option could be to automatically “promote” the constructors of a variant into records. That is, if you wrote:

```
type ExampleUnion = A { aField : String } | B { bField : Int }
```

it would implicitly define

```
type A = { aField : String }

type B = { bField : Int }
```

this already happens at the Avro level, so I don't think it would change anything there. It also works this way in the Python code generation where each of the constructors is its own class.

However, I'm not sure what this would look like for the Haskell (and Rust?) code generation. The problem is that we'd want to use `A` as a constructor for *both* the `A` record type *and* the `ExampleUnion` sum type, and there's no equivalent of `DuplicateFieldNames` for constructors!

I hadn't considered this “promoting” earlier, so it would be a real shift from the current behavior. Now that I'm thinking about it more, I definitely like the idea, but would need to come up with something reasonable on the Haskell side...

This is very much not the first time that I've wished we could define record types in Haskell without needing a constructor. Anonymous sums/records and row types are probably the number one feature I'm missing from the language.
