### ISSUE TITLE
Status of default values

### ISSUE THREAD

**Issue by pasunboneleve** [target/theta-idl#70]
Does **theta-idl** allows the definition of default values? So that we could define a new field with a default value and be able to decode an older schema without issues? What would it take to implement such solution?

**Comment by TikhonJelvis** [comment]
There is currently no support for default values. Supporting this would require some easy changes to Theta's core (parsing, `Theta.Type`) but would also require some broader changes to the Haskell, Python and Rust code generation. We would need to change the parsing APIs to handle different reader and writer schemas, as well as substantially changing the generated parsing code.

Right now, the parsing code generated for a record type constructs the record directly. In pseudocode, if we have a record like

```
type Example = { a : Int, b : Double, c : String }
```

then the generated code will look like:

```
do a <- parseInt
   b <- parseDouble
   c <- parseString
   pure (Example a b c)
```

To support default values, we'd have to change the modified code so that it could take the writer schema, use that to figure out which fields need default values and handle that during parsing. I see two options for doing this:

  1. Generate some kind of "parse with default" function that takes a writer schema, a default and a parser and handles the defaulting logic.
  
  2. Switch to using an intermediate type for records (eg `HashMap Text Theta.Value`) rather than constructing record values directly.
  
Option 1 would be a smaller change and would support default values, but would not provide a clear path to supporting other kinds of schema evolution (like changing the *order* of the fields). I've spent a decent amount of time thinking about how to support schema evolution without an intermediate type, but have not been able to come up with a satisfactory design.

Option 2 would require a larger change to the code but would make it easy to support other kinds of schema evolution and backwards compatibility in the future. My original implementation in Haskell used an intermediate type to parse values—in fact, most of the code is still there to work with `Theta.Value` and `Avro.Value`—but that version of the code  leaked *a lot* of memory on larger inputs. I remember investigating this with @alexbiehl but we could not figure out how to fix the problem which is why I went with a design that did *not* use an intermediate type. It looks like the Haskell Avro package has a parser that uses `Avro.Value` as an intermediate type, so perhaps there is a way to do this without running into memory leaks.

I kept the same design for the generated Python and Rust code, but I am not sure that it is necessary for performance reasons in either case.

Either of these options has the potential to affect the performance of the generated code, so having some larger benchmarks to measure the effect would be useful.

I do not have the time and energy at the moment to make these changes on my own, but I'm always happy to help if somebody else wants to give it a try.
